orbs:
  macos: circleci/macos@2.5.1
  slack: circleci/slack@4.10.1
  # Disabled until compatible with M1: codecov: codecov/codecov@3.3.0
  # codecov: codecov/codecov@3.3.0

version: 2.1

parameters:
  action:
    type: enum
    enum: [default, bump, run-manual-tests]
    default: default
  generate_snapshots:
    default: false
    type: boolean
  generate_revenuecatui_snapshots:
    default: false
    type: boolean

aliases:
  base-job: &base-job
    resource_class: macos.m1.medium.gen1
    macos:
      xcode: << parameters.xcode_version >>
    parameters:
      xcode_version:
        type: string
        default: '15.3'
      install_swiftlint:
        type: boolean
        default: true
    environment:
      CIRCLECI_TESTS_GENERATE_SNAPSHOTS: << pipeline.parameters.generate_snapshots >>
      CIRCLECI_TESTS_GENERATE_REVENUECAT_UI_SNAPSHOTS: << pipeline.parameters.generate_revenuecatui_snapshots >>
    working_directory: ~/purchases-ios
    shell: /bin/bash --login -o pipefail
  release-branches: &release-branches
    filters:
      tags:
        ignore: /.*/
      branches:
        only: /^release\/.*/
  release-tags: &release-tags
    filters:
      tags:
        ignore: /^.*-SNAPSHOT/
      branches:
        ignore: /.*/
  release-branches-and-main: &release-branches-and-main
    filters:
      tags:
        ignore: /.*/
      branches:
        only:
          - main
          - paywalls
          - /^release\/.*/
  only-main-branch: &only-main-branch
    filters:
      tags:
        ignore: /.*/
      branches:
        only: main
  non-patch-release-branches: &non-patch-release-branches
    filters:
      tags:
        ignore: /.*/
      branches:
        only: /^release\/.*\.0$/

  # Forked pull requests have CIRCLE_BRANCH set to pull/XXX
  forked-pull-requests: &forked-pull-requests
    filters:
      tags:
        ignore: /pull\/[0-9]+/
